// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE3ETaYRsbDgYVV3OmiWoIYVL_LDv8G9M',
    appId: '1:825148335086:web:8aeedb09b9d4fc160a24ff',
    messagingSenderId: '825148335086',
    projectId: 'aamecom-22dc0',
    authDomain: 'aamecom-22dc0.firebaseapp.com',
    storageBucket: 'aamecom-22dc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZACnoSmHfHUs2dAwaE-t0f7vBW4HZ7U',
    appId: '1:825148335086:android:07f22562d445abc60a24ff',
    messagingSenderId: '825148335086',
    projectId: 'aamecom-22dc0',
    storageBucket: 'aamecom-22dc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdybd37eOA4sP_RbWPiWJWJJ6XAtkriq0',
    appId: '1:825148335086:ios:31fb0263e346fda40a24ff',
    messagingSenderId: '825148335086',
    projectId: 'aamecom-22dc0',
    storageBucket: 'aamecom-22dc0.appspot.com',
    iosClientId: '825148335086-dojlbrvfucvafnlosaac1dgq85it9gan.apps.googleusercontent.com',
    iosBundleId: 'com.example.amEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdybd37eOA4sP_RbWPiWJWJJ6XAtkriq0',
    appId: '1:825148335086:ios:621f921f3dcf5d660a24ff',
    messagingSenderId: '825148335086',
    projectId: 'aamecom-22dc0',
    storageBucket: 'aamecom-22dc0.appspot.com',
    iosClientId: '825148335086-slk9b1l9a09vdlor72jtnvjgfqh2uvld.apps.googleusercontent.com',
    iosBundleId: 'com.example.amEcom.RunnerTests',
  );
}
